package tad.entity;
// Generated Apr 8, 2023, 3:38:47 PM by Hibernate Tools 3.6.2.Final

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "Coupon", schema = "dbo", catalog = "DB_Tad")
public class Coupon {
	@Id
	@GeneratedValue
	@Column(name = "CouponID", unique = true, nullable = false)
	private int couponId;

	@Column(name = "Name", nullable = false)
	private String name;

	@Column(name = "Discount", nullable = false, precision = 53, scale = 0)
	private double discount;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostingDate", nullable = false, length = 23)
	private Date postingDate;

	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(pattern = "dd-MM-yyyy HH:mm:ss")
	@Column(name = "ExpiryDate", nullable = false, length = 23)
	private Date expiryDate;

	@Column(name = "Detail")
	private String detail;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountID", nullable = false, updatable = true)
	private Account account;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	private Set<Product> products = new HashSet<>(0);

	public boolean checkVaildCoupon() {

		try {
			Date in = new Date();
			LocalDateTime ldt = LocalDateTime.ofInstant(in.toInstant(), ZoneId.systemDefault());
			Date crrdate = Date.from(ldt.atZone(ZoneId.systemDefault()).toInstant());

			if (crrdate.before(postingDate) || crrdate.after(expiryDate)) {
				return false;
			}

		} catch (Exception e) {
		}
		return true;
	}

	public Coupon() {
	}

	public Coupon(int couponId, boolean typeCoupon, String name, double discount, Date postingDate, Date expiryDate) {
		this.couponId = couponId;
		this.name = name;
		this.discount = discount;
		this.postingDate = postingDate;
		this.expiryDate = expiryDate;

	}

	public Coupon(int couponId, boolean typeCoupon, String name, double discount, Date postingDate, Date expiryDate,
			String detail, Set<Product> products) {
		this.couponId = couponId;
		this.name = name;
		this.discount = discount;
		this.postingDate = postingDate;
		this.expiryDate = expiryDate;
		this.detail = detail;
		this.products = products;
	}

	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
